### ISSUE TITLE
NDVI data download and preprocessing

### ISSUE THREAD

**Issue by ymutua** [Chimbioputo1980/LDN_Namibia#1]
Download and preprocess MODIS NDVI MOD44 (MODAPS) (C6) images

**Comment by eheikomuni** [comment]
Thanks John, I am on it right away, Sir!!!

**Comment by ymutua** [comment]
Code has been updated

**Comment by simeonhengari** [comment]
John, I saw this option to run R on Ubuntu but not sure if this would work for our case:
https://www.digitalocean.com/community/tutorials/how-to-set-up-r-on-ubuntu-14-04

Let me know your thoughts

**Comment by simeonhengari** [comment]
Erlich, the option for UNAM is only for us to download and save data on their server, but we may not be able to run the R image analysis there, according to my last call with Simon, he will update you with more details
