### ISSUE TITLE
Finalize DSM workflow document

### ISSUE THREAD

**Issue by bkempen** [Chimbioputo1980/LDN_Namibia#5]
Finalize and share DSM workflow document.

**Comment by simeonhengari** [comment]
Hi Bas, do you already have a description for preparing the covariate stacks that can be added to the Workflow?
I think it would be good to include this as we will have to prepare new stacks for the next regions.

**Comment by bkempen** [comment]
I do not plan to do this. This are basic GIS analyses: transforming, clipping, projecting etc.  I have pointed out where to find the covariates for Namibia at 1km resolution, and upon request we can make the entire stack available at 250m. Then the only thing that needs to be done is to clip the layers for the area of interest.

**Comment by simeonhengari** [comment]
Ok Bas, I understand. What is the best way to send the request for the Namibian 250m stack?

**Comment by bkempen** [comment]
Just send me an email when a new project is planned.

**Comment by simeonhengari** [comment]
Ok, I wanted to run a test on another region for which the Agriculture Soil lab have soil data available in their data base, i.e. Omaheke region. I had a chat with their Soil lab manager and they are interested  to see if mapping can be done with the data they have.

**Comment by bkempen** [comment]
for this purpose I would collect the namibia covariates at 1km resolution from ftp://isric.org [gsp, gspisric].

**Comment by simeonhengari** [comment]
Ok thanks, will look at the regional data and see more what they have and come back to you, especially if they have to work on data for Min. of Agriculture experimental farms for which they have more data. Thanks for the quick responses.

**Comment by bkempen** [comment]
I uploaded a script to download TIF layers from an ftp server (in the SOC mapping folder). It also shows how to reproject these layers (requires installation of gdal): http://www.gisinternals.com/release.php

**Comment by simeonhengari** [comment]
Thanks, will give it a try and come back if I have issues.
